# Site settings
title: CloudsFm | 浮云频率
description: "想到哪写到哪。"
url: "http://cloudsfm.net/"
author:
  name: "CloudsFm"
  email: "@"
  url: "http://cloudsfm.net/"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
allowedFields: ['name', 'email', 'comment']

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
